== The Internals of Spark Structured Streaming (Apache Spark {{ book.version }})

Welcome to *The Internals of Spark Structured Streaming* gitbook! I'm very excited to have you here and hope you will enjoy exploring the internals of Spark Structured Streaming as much as I have.

[quote, Flannery O'Connor]
I write to discover what I know.

I'm https://pl.linkedin.com/in/jaceklaskowski[Jacek Laskowski], a freelance IT consultant, software engineer and technical instructor specializing in https://spark.apache.org/[Apache Spark], https://kafka.apache.org/[Apache Kafka] and https://kafka.apache.org/documentation/streams/[Kafka Streams] (with https://www.scala-lang.org/[Scala] and https://www.scala-sbt.org/[sbt]).

I offer software development and consultancy services with hands-on in-depth workshops and mentoring. Reach out to me at jacek@japila.pl or https://twitter.com/jaceklaskowski[@jaceklaskowski] to discuss opportunities.

Consider joining me at http://www.meetup.com/WarsawScala/[Warsaw Scala Enthusiasts] and http://www.meetup.com/Warsaw-Spark[Warsaw Spark] meetups in Warsaw, Poland.

TIP: I'm also writing other books in the "The Internals of" series about http://books.japila.pl/apache-spark-internals[Apache Spark], https://bit.ly/spark-sql-internals[Spark SQL], https://bit.ly/apache-kafka-internals[Apache Kafka], and https://bit.ly/kafka-streams-internals[Kafka Streams].

Expect text and code snippets from a variety of public sources. Attribution follows.

Now, let me introduce you to <<spark-structured-streaming.adoc#, Spark Structured Streaming and Streaming Queries>>.
