== Streaming Operators / Streaming Dataset API

Dataset API has a set of <<operators, operators>> that are of particular use in Apache Spark's Structured Streaming that together constitute so-called *Streaming Dataset API*.

[[operators]]
.Streaming Operators
[cols="1,3",options="header",width="100%"]
|===
| Operator
| Description

| [[dropDuplicates]] link:spark-sql-streaming-Dataset-dropDuplicates.adoc[dropDuplicates]
a| Drops duplicate records (given a subset of columns)

[source, scala]
----
dropDuplicates(): Dataset[T]
dropDuplicates(colNames: Seq[String]): Dataset[T]
dropDuplicates(col1: String, cols: String*): Dataset[T]
----

| [[explain]] link:spark-sql-streaming-Dataset-explain.adoc[explain]
a| Explains execution plans

[source, scala]
----
explain(): Unit
explain(extended: Boolean): Unit
----

| [[groupBy]] link:spark-sql-streaming-Dataset-groupBy.adoc[groupBy]
a| Aggregates rows by a untyped grouping function

[source, scala]
----
groupBy(cols: Column*): RelationalGroupedDataset
groupBy(col1: String, cols: String*): RelationalGroupedDataset
----

| [[groupByKey]] link:spark-sql-streaming-Dataset-groupByKey.adoc[groupByKey]
a| Aggregates rows by a typed grouping function

[source, scala]
----
groupByKey(func: T => K): KeyValueGroupedDataset[K, T]
----

| [[withWatermark]] <<withWatermark-indepth, withWatermark>>
a| Defines a streaming watermark on a event time column

[source, scala]
----
withWatermark(eventTime: String, delayThreshold: String): Dataset[T]
----
|===

[source, scala]
----
scala> spark.version
res0: String = 2.3.0-SNAPSHOT

// input stream
val rates = spark.
  readStream.
  format("rate").
  option("rowsPerSecond", 1).
  load

// stream processing
// replace [operator] with the operator of your choice
rates.[operator]

// output stream
import org.apache.spark.sql.streaming.{OutputMode, Trigger}
import scala.concurrent.duration._
val sq = rates.
  writeStream.
  format("console").
  option("truncate", false).
  trigger(Trigger.ProcessingTime(10.seconds)).
  outputMode(OutputMode.Complete).
  queryName("rate-console").
  start

// eventually...
sq.stop
----

=== [[withWatermark-indepth]] Specifying Event Time Watermark -- `withWatermark` Operator

[source, scala]
----
withWatermark(eventTime: String, delayThreshold: String): Dataset[T]
----

CAUTION: FIXME
