== [[UnsupportedOperationChecker]] UnsupportedOperationChecker

`UnsupportedOperationChecker` checks whether the <<checkForStreaming, logical plan of a streaming query uses supported operations only>>.

NOTE: `UnsupportedOperationChecker` is used exclusively when the internal link:spark-sql-streaming-properties.adoc#spark.sql.streaming.unsupportedOperationCheck[spark.sql.streaming.unsupportedOperationCheck] Spark property is enabled (which is by default).

[NOTE]
====
`UnsupportedOperationChecker` comes actually with two methods, i.e. `checkForBatch` and <<checkForStreaming, checkForStreaming>>, whose names reveal the different flavours of Spark SQL (as of 2.0), i.e. batch and streaming, respectively.

The Spark Structured Streaming gitbook is solely focused on <<checkForStreaming, checkForStreaming>> method.
====

=== [[checkForStreaming]] `checkForStreaming` Method

[source, scala]
----
checkForStreaming(plan: LogicalPlan, outputMode: OutputMode): Unit
----

`checkForStreaming`...FIXME

`checkForStreaming` counts all link:spark-sql-streaming-FlatMapGroupsWithState.adoc[FlatMapGroupsWithState] logical operators (on streaming Datasets with `isMapGroupsWithState` flag disabled).

NOTE: link:spark-sql-streaming-FlatMapGroupsWithState.adoc[FlatMapGroupsWithState] logical operator represents link:spark-sql-streaming-KeyValueGroupedDataset.adoc#mapGroupsWithState[mapGroupsWithState] and link:spark-sql-streaming-KeyValueGroupedDataset.adoc#flatMapGroupsWithState[flatMapGroupsWithState] operators.

NOTE: link:spark-sql-streaming-FlatMapGroupsWithState.adoc#isMapGroupsWithState[FlatMapGroupsWithState.isMapGroupsWithState] flag is disabled when...FIXME

[[multiple-flatMapGroupsWithState]]
`checkForStreaming` asserts that multiple link:spark-sql-streaming-FlatMapGroupsWithState.adoc[FlatMapGroupsWithState] logical operators are only used when:

* `outputMode` is link:spark-sql-streaming-OutputMode.adoc#Append[Append] output mode

* link:spark-sql-streaming-FlatMapGroupsWithState.adoc#outputMode[outputMode] of the `FlatMapGroupsWithState` logical operators is also link:spark-sql-streaming-OutputMode.adoc#Append[Append] output mode

CAUTION: FIXME Reference to an example in `flatMapGroupsWithState`

Otherwise, `checkForStreaming` reports a `AnalysisException`:

[options="wrap"]
----
Multiple flatMapGroupsWithStates are not supported when they are not all in append mode or the output mode is not append on a streaming DataFrames/Datasets
----

CAUTION: FIXME

NOTE: `checkForStreaming` is used exclusively when `StreamingQueryManager` is requested to link:spark-sql-streaming-StreamingQueryManager.adoc#createQuery[create a StreamingQueryWrapper] (for starting a streaming query), but only when the internal link:spark-sql-streaming-properties.adoc#spark.sql.streaming.unsupportedOperationCheck[spark.sql.streaming.unsupportedOperationCheck] Spark property is enabled (which is by default).
