== [[StreamingRelation]] StreamingRelation Leaf Logical Operator

`StreamingRelation` is a leaf logical operator (i.e. `LogicalPlan`) that is <<creating-instance, created>> when `DataStreamReader` is requested to link:spark-sql-streaming-DataStreamReader.adoc#load[load] dataset in streaming fashion (and create a streaming `Dataset`).

NOTE: `StreamingRelation` is link:spark-sql-streaming-StreamExecution.adoc#logicalPlan[resolved] (aka _converted_) to link:spark-sql-streaming-StreamingExecutionRelation.adoc[StreamingExecutionRelation] (right after `StreamExecution` started link:spark-sql-streaming-StreamExecution.adoc#runBatches[running batches]).

[source, scala]
----
val rate = spark.
  readStream.
  format("rate").
  load("hello")
scala> println(rate.queryExecution.logical.numberedTreeString)
00 StreamingRelation DataSource(org.apache.spark.sql.SparkSession@4e5dcc50,rate,List(),None,List(),None,Map(path -> hello),None), rate, [timestamp#0, value#1L]
----

[[isStreaming]]
`isStreaming` is always enabled (i.e. `true`).

[source, scala]
----
import org.apache.spark.sql.execution.streaming.StreamingRelation
val relation = rate.queryExecution.logical.asInstanceOf[StreamingRelation]
scala> relation.isStreaming
res1: Boolean = true
----

[[toString]]
`toString` gives the <<sourceName, source name>>.

[source, scala]
----
scala> println(relation)
rate
----

=== [[creating-instance]] Creating StreamingRelation Instance

`StreamingRelation` takes the following when created:

* [[dataSource]] `DataSource`
* [[sourceName]] Source name
* [[output]] Output attributes
