== [[StateStoreCoordinatorRef]] StateStoreCoordinatorRef Interface for Communication with StateStoreCoordinator

[[rpcEndpointRef]]
`StateStoreCoordinatorRef` allows for <<messages, communication>> with link:spark-sql-streaming-StateStoreCoordinator.adoc[StateStoreCoordinator] (through `rpcEndpointRef` reference).

[[messages]]
.StateStoreCoordinatorRef's Methods and Underlying RPC Messages (in alphabetical order)
[width="100%",cols="1,1,2",options="header"]
|===
| Method
| RPC Message
| Description

| [[deactivateInstances]] `deactivateInstances`
| `DeactivateInstances`
a| Synchronous event to announce that `StreamingQueryManager` link:spark-sql-streaming-StreamingQueryManager.adoc#notifyQueryTermination[has been informed that a query terminated] (which is when `StreamExecution` link:spark-sql-streaming-StreamExecution.adoc#runBatches-finally[has finished (running streaming batches)]).

NOTE: Refer to link:spark-sql-streaming-StateStoreCoordinator.adoc#DeactivateInstances[DeactivateInstances] (of `StateStoreCoordinator`) to know how the event is handled.

| [[getLocation]] `getLocation`
| `GetLocation`
|

| [[reportActiveInstance]] `reportActiveInstance`
| `ReportActiveInstance`
|

| [[stop]] `stop`
| `StopCoordinator`
|

| [[verifyIfInstanceActive]] `verifyIfInstanceActive`
| `VerifyIfInstanceActive`
|
|===

=== [[forDriver]] Creating StateStoreCoordinatorRef with StateStoreCoordinator RPC Endpoint -- `forDriver` Method

[source, scala]
----
forDriver(env: SparkEnv): StateStoreCoordinatorRef
----

`forDriver`...FIXME

NOTE: `forDriver` is used exclusively when `StreamingQueryManager` link:spark-sql-streaming-StreamingQueryManager.adoc#creating-instance[is created].

=== [[forExecutor]] `forExecutor` Method

[source, scala]
----
forExecutor(env: SparkEnv): StateStoreCoordinatorRef
----

`forExecutor`...FIXME

NOTE: `forExecutor` is used exclusively when `StateStore` link:spark-sql-streaming-StateStore.adoc#coordinatorRef[creates a StateStoreCoordinatorRef (for executors)].
