== [[EventTimeWatermark]] EventTimeWatermark Unary Logical Operator

`EventTimeWatermark` is a unary logical operator (i.e. `UnaryNode`) that is <<creating-instance, created>> as the result of link:spark-sql-streaming-Dataset-withWatermark.adoc[withWatermark] operator.

[source, scala]
----
val q = spark.
  readStream.
  format("rate").
  load.
  withWatermark(eventTime = "timestamp", delayThreshold = "30 seconds") // <-- creates EventTimeWatermark
scala> q.explain(extended = true)
== Parsed Logical Plan ==
'EventTimeWatermark 'timestamp, interval 30 seconds
+- StreamingRelation DataSource(org.apache.spark.sql.SparkSession@3d97b0a,rate,List(),None,List(),None,Map(),None), rate, [timestamp#10, value#11L]

== Analyzed Logical Plan ==
timestamp: timestamp, value: bigint
EventTimeWatermark timestamp#10: timestamp, interval 30 seconds
+- StreamingRelation DataSource(org.apache.spark.sql.SparkSession@3d97b0a,rate,List(),None,List(),None,Map(),None), rate, [timestamp#10, value#11L]

== Optimized Logical Plan ==
EventTimeWatermark timestamp#10: timestamp, interval 30 seconds
+- StreamingRelation DataSource(org.apache.spark.sql.SparkSession@3d97b0a,rate,List(),None,List(),None,Map(),None), rate, [timestamp#10, value#11L]

== Physical Plan ==
EventTimeWatermark timestamp#10: timestamp, interval 30 seconds
+- StreamingRelation rate, [timestamp#10, value#11L]
----

[[watermarkDelayMs]]
[[delayKey]]
`EventTimeWatermark` uses `spark.watermarkDelayMs` key (in `Metadata` in <<output, output>>) to hold the event-time watermark delay.

NOTE: The *event-time watermark delay* is used to calculate the difference between the event time of an event (that is modelled as a row in the Dataset for a streaming batch) and the time in the past.

[NOTE]
====
`EliminateEventTimeWatermark` logical optimization rule (i.e. `Rule[LogicalPlan]`) removes `EventTimeWatermark` logical operator from a logical plan if <<child, child>> logical operator is not streaming, i.e. when link:spark-sql-streaming-Dataset-withWatermark.adoc[withWatermark] operator is used on a batch query.

[source, scala]
----
val logs = spark.
  read. // <-- batch non-streaming query that makes `EliminateEventTimeWatermark` rule applicable
  format("text").
  load("logs")

// logs is a batch Dataset
scala> logs.isStreaming
res0: Boolean = false

val q = logs.
  withWatermark(eventTime = "timestamp", delayThreshold = "30 seconds") // <-- creates EventTimeWatermark
scala> println(q.queryExecution.logical.numberedTreeString) // <-- no EventTimeWatermark as it was removed immediately
00 Relation[value#0] text
----
====

NOTE: `EventTimeWatermark` is converted (aka _planned_) to link:spark-sql-streaming-EventTimeWatermarkExec.adoc[EventTimeWatermarkExec] physical operator in link:spark-sql-streaming-StatefulAggregationStrategy.adoc[StatefulAggregationStrategy] execution planning strategy.

=== [[output]] `output` Property

[source, scala]
----
output: Seq[Attribute]
----

NOTE: `output` is a part of the `QueryPlan` Contract to describe the attributes of (the schema of) the output.

`output` finds <<eventTime, eventTime>> column in the <<child, child>>'s output schema and updates the `Metadata` of the column with <<delayKey, spark.watermarkDelayMs>> key and the milliseconds for the delay.

`output` removes <<delayKey, spark.watermarkDelayMs>> key from the other columns.

[source, scala]
----
// See q created above
// FIXME How to access/show the eventTime column with the metadata updated to include spark.watermarkDelayMs?
import org.apache.spark.sql.catalyst.plans.logical.EventTimeWatermark
val etw = q.queryExecution.logical.asInstanceOf[EventTimeWatermark]
scala> etw.output.toStructType.printTreeString
root
 |-- timestamp: timestamp (nullable = true)
 |-- value: long (nullable = true)
----

=== [[creating-instance]] Creating EventTimeWatermark Instance

`EventTimeWatermark` takes the following when created:

* [[eventTime]] Event time column
* [[delay]] Delay `CalendarInterval`
* [[child]] Child logical plan
