== [[EventTimeWatermark]] EventTimeWatermark Unary Logical Operator -- Streaming Watermark

`EventTimeWatermark` is a unary logical operator that is <<creating-instance, created>> to represent <<spark-sql-streaming-Dataset-operators.adoc#withWatermark, Dataset.withWatermark>> operator in a logical query plan of a streaming query.

[NOTE]
====
A unary logical operator (`UnaryNode`) is a logical operator with a single <<child, child>> logical operator.

Read up on https://jaceklaskowski.gitbooks.io/mastering-spark-sql/spark-sql-LogicalPlan.html[UnaryNode] (and logical operators in general) in https://bit.ly/spark-sql-internals[The Internals of Spark SQL] book.
====

`EventTimeWatermark` is resolved (aka _planned_) to <<spark-sql-streaming-EventTimeWatermarkExec.adoc#, EventTimeWatermarkExec>> physical operator in <<spark-sql-streaming-StatefulAggregationStrategy.adoc#, StatefulAggregationStrategy>> execution planning strategy.

[NOTE]
====
`EliminateEventTimeWatermark` logical optimization rule (i.e. `Rule[LogicalPlan]`) removes `EventTimeWatermark` logical operator from a logical plan if the <<child, child>> logical operator is not streaming, i.e. when <<spark-sql-streaming-Dataset-operators.adoc#withWatermark, Dataset.withWatermark>> operator is used on a batch query.

[source, scala]
----
val logs = spark.
  read. // <-- batch non-streaming query that makes `EliminateEventTimeWatermark` rule applicable
  format("text").
  load("logs")

// logs is a batch Dataset
assert(!logs.isStreaming)

val q = logs.
  withWatermark(eventTime = "timestamp", delayThreshold = "30 seconds") // <-- creates EventTimeWatermark
scala> println(q.queryExecution.logical.numberedTreeString) // <-- no EventTimeWatermark as it was removed immediately
00 Relation[value#0] text
----
====

=== [[creating-instance]] Creating EventTimeWatermark Instance

`EventTimeWatermark` takes the following to be created:

* [[eventTime]] Name of the column for <<spark-sql-streaming-watermark.adoc#, event-time watermark>>
* [[delay]] Delay (`CalendarInterval`)
* [[child]] Child logical operator (`LogicalPlan`)

=== [[output]] Output Schema -- `output` Property

[source, scala]
----
output: Seq[Attribute]
----

NOTE: `output` is part of the `QueryPlan` Contract to describe the attributes of (the schema of) the output.

`output` finds <<eventTime, eventTime>> column in the output schema of the <<child, child>> logical operator and updates the `Metadata` of the column with <<delayKey, spark.watermarkDelayMs>> key and the milliseconds for the delay.

`output` removes <<delayKey, spark.watermarkDelayMs>> key from the other columns.

[source, scala]
----
// FIXME How to access/show the eventTime column with the metadata updated to include spark.watermarkDelayMs?
import org.apache.spark.sql.catalyst.plans.logical.EventTimeWatermark
val etw = q.queryExecution.logical.asInstanceOf[EventTimeWatermark]
scala> etw.output.toStructType.printTreeString
root
 |-- timestamp: timestamp (nullable = true)
 |-- value: long (nullable = true)
----

=== [[watermarkDelayMs]][[delayKey]] `spark.watermarkDelayMs` Metadata Key

`EventTimeWatermark` uses *spark.watermarkDelayMs* key (in the `Metadata` of the <<output, output attributes>>) to hold the event-time watermark delay (as a so-called _watermark attribute_ or _eventTime watermark_).

The *event-time watermark delay* is used to calculate the difference between the event time of an event (modeled as a row in the streaming Dataset) and the time in the past.
