== [[StreamSourceProvider]] StreamSourceProvider -- Streaming Data Source Provider

`StreamSourceProvider` is a <<contract, contract>> for objects that can <<createSource, create a streaming data source>> for a format (e.g. text file) or system (e.g. Apache Kafka) by their short names.

`StreamSourceProvider` is used when `DataSource` is requested for the link:spark-sql-datasource.adoc#sourceSchema[name and schema of a streaming source] or just link:spark-sql-datasource.adoc#createSource[creates one].

.Streaming Source Providers (in alphabetical order)
[cols="1,3",options="header",width="100%"]
|===
| Name
| Description

| link:spark-sql-streaming-KafkaSourceProvider.adoc[KafkaSourceProvider]
| Creates link:spark-sql-streaming-KafkaSourceProvider.adoc[KafkaSourceProvider] for `kafka` format.

| link:spark-sql-streaming-TextSocketSourceProvider.adoc[TextSocketSourceProvider]
| Creates link:spark-sql-streaming-TextSocketSource.adoc[TextSocketSources] for `socket` format.
|===

=== [[contract]] StreamSourceProvider Contract

[source, scala]
----
trait StreamSourceProvider {
  def sourceSchema(
      sqlContext: SQLContext,
      schema: Option[StructType],
      providerName: String,
      parameters: Map[String, String]): (String, StructType)
  def createSource(
      sqlContext: SQLContext,
      metadataPath: String,
      schema: Option[StructType],
      providerName: String,
      parameters: Map[String, String]): Source
}
----

NOTE: `StreamSourceProvider` is an experimental contract.

.StreamSourceProvider Contract (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[createSource]] `createSource`
a|

Creates a link:spark-sql-streaming-Source.adoc[streaming source] for a format or system (to continually read data).

NOTE: `metadataPath` is the value of the optional user-specified `checkpointLocation` option or resolved by link:spark-sql-streaming-StreamingQueryManager.adoc#createQuery[StreamingQueryManager].

Used exclusively when Spark SQL's `DataSource` is requested for a `Source` for a `StreamSourceProvider` (which is when `StreamingRelation` is requested for a logical plan).

TIP: Read https://jaceklaskowski.gitbooks.io/mastering-apache-spark/spark-sql-datasource.html[DataSource &mdash; Pluggable Data Sources].

| [[sourceSchema]] `sourceSchema`
| link:spark-sql-streaming-Source.adoc[Source] name and the schema of records
|===
