== Streaming Join

In Spark Structured Streaming, a *streaming join* is a streaming query that was described (_build_) using the <<spark-sql-streaming-Dataset-operators.adoc#, high-level streaming operators>>:

* <<spark-sql-streaming-Dataset-operators.adoc#crossJoin, Dataset.crossJoin>>

* <<spark-sql-streaming-Dataset-operators.adoc#join, Dataset.join>>

* <<spark-sql-streaming-Dataset-operators.adoc#joinWith, Dataset.joinWith>>

* SQL's `JOIN` clause

Streaming joins can be *stateless* or <<spark-sql-streaming-stateful-stream-processing.adoc#, stateful>>:

* Joins of a streaming query and a batch query (aka _stream-static joins_) are stateless and no state management is required

* Joins of two streaming queries (aka <<stream-stream-joins, stream-stream joins>>) are stateful and require streaming state (with a <<spark-sql-streaming-watermark.adoc#, streaming watermark>>).

=== [[stream-stream-joins]] Stream-Stream Equi-Joins

A stream-stream equi-join is planned as <<spark-sql-streaming-StreamingSymmetricHashJoinExec.adoc#, StreamingSymmetricHashJoinExec>> physical operator of two `ShuffleExchangeExec` physical operators (per <<spark-sql-streaming-StreamingSymmetricHashJoinExec.adoc#requiredChildDistribution, Required Partition Requirements>>).

Spark Structured Streaming supports stream-stream joins with the following:

* <<spark-sql-streaming-StreamingJoinStrategy.adoc#, Equality predicate>> (https://en.wikipedia.org/wiki/Join_(SQL)#Equi-join[equi-joins] that use only equality comparisons in the join-predicate)

* `Inner`, `LeftOuter`, and `RightOuter` <<spark-sql-streaming-StreamingSymmetricHashJoinExec.adoc#supported-join-types, join types only>>

=== [[IncrementalExecution]] IncrementalExecution -- QueryExecution of Streaming Queries

Under the covers, the high-level operators create a logical query plan with one or more `Join` logical operators.

TIP: Read up on https://jaceklaskowski.gitbooks.io/mastering-spark-sql/spark-sql-LogicalPlan-Join.html[Join Logical Operator] in https://bit.ly/spark-sql-internals[The Internals of Spark SQL] book.

In Spark Structured Streaming <<spark-sql-streaming-IncrementalExecution.adoc#, IncrementalExecution>> is responsible for planning streaming queries for execution.

At <<spark-sql-streaming-IncrementalExecution.adoc#executedPlan, query planning>>, `IncrementalExecution` uses the <<spark-sql-streaming-StreamingJoinStrategy.adoc#, StreamingJoinStrategy>> execution planning strategy for planning <<stream-stream-joins, stream-stream joins>> as <<spark-sql-streaming-StreamingSymmetricHashJoinExec.adoc#, StreamingSymmetricHashJoinExec>> physical operators.

=== [[demos]] Demos

Use the following demos to learn more:

* <<spark-sql-streaming-demo-join-stream-stream-StreamingSymmetricHashJoinExec.adoc#, Demo: Streaming Join of Streaming Queries and StreamingSymmetricHashJoinExec Physical Operator>>
