== [[StateStoreSaveExec]] StateStoreSaveExec -- Unary Physical Operator for Saving Streaming Aggregates

`StateStoreSaveExec` is a unary physical operator (i.e. `UnaryExecNode`) that link:spark-sql-streaming-StateStoreWriter.adoc[writes state to StateStore] and link:spark-sql-streaming-WatermarkSupport.adoc[supports streaming watermark].

`StateStoreSaveExec` is <<creating-instance, created>> exclusively when `StatefulAggregationStrategy` link:spark-sql-streaming-StatefulAggregationStrategy.adoc#apply[plans a streaming aggregation].

[source, scala]
----
val counts = spark.
  readStream.
  format("rate").
  load.
  groupBy(window($"timestamp", "5 seconds") as "group").
  agg(count("value") as "count").
  orderBy("group")

----

`StateStoreSaveExec` is...FIXME...`IncrementalExecution#state`

[[output]]
The output schema of `StateStoreSaveExec` is exactly the <<child, child>>'s output schema.

[source, scala]
----
...FIXME
----

[[outputPartitioning]]
The output partitioning of `StateStoreSaveExec` is exactly the <<child, child>>'s output partitioning.

[source, scala]
----
...FIXME
----

=== [[doExecute]] `doExecute` Method

CAUTION: FIXME

==== [[doExecute-Update]] Update Output Mode

CAUTION: FIXME

=== [[creating-instance]] Creating StateStoreSaveExec Instance

`StateStoreSaveExec` takes the following when created:

* [[keyExpressions]] Catalyst expressions for keys
* [[stateInfo]] Optional `StatefulOperatorStateInfo`
* [[outputMode]] Optional link:spark-sql-streaming-OutputMode.adoc[output mode]
* [[eventTimeWatermark]] Optional event time watermark
* [[child]] Child physical plan (i.e. `SparkPlan`)
