== Configuration Properties

Configuration properties are used to fine-tune Spark Structured Streaming applications.

You can set them for a `SparkSession` when it is created using `config` method.

[source, scala]
----
import org.apache.spark.sql.SparkSession
val spark = SparkSession
  .builder
  .config("spark.sql.streaming.metricsEnabled", true)
  .getOrCreate
----

TIP: Read up on https://jaceklaskowski.gitbooks.io/mastering-spark-sql/spark-sql-SparkSession.html[SparkSession] in https://bit.ly/spark-sql-internals[The Internals of Spark SQL] book.

[[properties]]
.Structured Streaming's Properties
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| spark.sql.streaming.aggregation.stateFormatVersion
a| [[spark.sql.streaming.aggregation.stateFormatVersion]] *(internal)* Version of the state format

Default: `2`

Supported values:

* [[spark.sql.streaming.aggregation.stateFormatVersion-legacyVersion]] `1` (for the legacy <<spark-sql-streaming-StreamingAggregationStateManagerBaseImpl.adoc#StreamingAggregationStateManagerImplV1, StreamingAggregationStateManagerImplV1>>)

* [[spark.sql.streaming.aggregation.stateFormatVersion-default]] `2` (for the default <<spark-sql-streaming-StreamingAggregationStateManagerBaseImpl.adoc#StreamingAggregationStateManagerImplV2, StreamingAggregationStateManagerImplV2>>)

Used when <<spark-sql-streaming-StatefulAggregationStrategy.adoc#, StatefulAggregationStrategy>> execution planning strategy is executed (and plans a streaming query with an aggregate that simply boils down to creating a <<spark-sql-streaming-StateStoreRestoreExec.adoc#, StateStoreRestoreExec>> with the proper _implementation version_ of <<spark-sql-streaming-StreamingAggregationStateManager.adoc#, StreamingAggregationStateManager>>)

Among the <<spark-sql-streaming-OffsetSeqMetadata.adoc#relevantSQLConfs, checkpointed properties>> that are not supposed to be overriden after a streaming query has once been started (and could later recover from a checkpoint after being restarted)

| spark.sql.streaming.checkpointLocation
a| [[spark.sql.streaming.checkpointLocation]] Default checkpoint directory for storing checkpoint data

Default: `(empty)`

| spark.sql.streaming.continuous.executorQueueSize
a| [[spark.sql.streaming.continuous.executorQueueSize]] *(internal)* The size (measured in number of rows) of the queue used in continuous execution to buffer the results of a ContinuousDataReader.

Default: `1024`

| spark.sql.streaming.continuous.executorPollIntervalMs
a| [[spark.sql.streaming.continuous.executorPollIntervalMs]] *(internal)* The interval (in millis) at which continuous execution readers will poll to check whether the epoch has advanced on the driver.

Default: `100` (ms)

| spark.sql.streaming.disabledV2MicroBatchReaders
a| [[spark.sql.streaming.disabledV2MicroBatchReaders]] *(internal)* A comma-separated list of fully-qualified class names of data source providers for which <<spark-sql-streaming-MicroBatchReadSupport.adoc#, MicroBatchReadSupport>> is disabled. Reads from these sources will fall back to the V1 Sources.

Default: `(empty)`

Use <<spark-sql-streaming-SQLConf.adoc#disabledV2StreamingMicroBatchReaders, SQLConf.disabledV2StreamingMicroBatchReaders>> to get the current value.

| spark.sql.streaming.flatMapGroupsWithState.stateFormatVersion
a| [[spark.sql.streaming.flatMapGroupsWithState.stateFormatVersion]] *(internal)* State format version used to create a <<spark-sql-streaming-StateManager.adoc#, StateManager>> for <<spark-sql-streaming-FlatMapGroupsWithStateExec.adoc#state-format-version, FlatMapGroupsWithStateExec>> physical operator

Default: `2`

Supported values:

* `1`
* `2`

Among the <<spark-sql-streaming-OffsetSeqMetadata.adoc#relevantSQLConfs, checkpointed properties>> that are not supposed to be overriden after a streaming query has once been started (and could later recover from a checkpoint after being restarted)

| spark.sql.streaming.maxBatchesToRetainInMemory
a| [[spark.sql.streaming.maxBatchesToRetainInMemory]] *(internal)* The maximum number of batches which will be retained in memory to avoid loading from files.

Default: `2`

Maximum count of versions a State Store implementation should retain in memory.

The value adjusts a trade-off between memory usage vs cache miss:

* `2` covers both success and direct failure cases
* `1` covers only success case
* `0` or negative value disables cache to maximize memory size of executors

Used exclusively when `HDFSBackedStateStoreProvider` is requested to <<spark-sql-streaming-HDFSBackedStateStoreProvider.adoc#init, initialize>>.

| spark.sql.streaming.metricsEnabled
| [[spark.sql.streaming.metricsEnabled]] Flag whether Dropwizard CodaHale metrics are reported for active streaming queries

Default: `false`

Use <<spark-sql-streaming-SQLConf.adoc#streamingMetricsEnabled, SQLConf.streamingMetricsEnabled>> to get the current value

| spark.sql.streaming.minBatchesToRetain
a| [[spark.sql.streaming.minBatchesToRetain]] *(internal)* The minimum number of entries to retain for failure recovery

Default: `100`

Use <<spark-sql-streaming-SQLConf.adoc#minBatchesToRetain, SQLConf.minBatchesToRetain>> to get the current value

| spark.sql.streaming.multipleWatermarkPolicy
a| [[spark.sql.streaming.multipleWatermarkPolicy]] *Global watermark policy* that is the policy to calculate the global watermark value when there are multiple watermark operators in a streaming query

Default: `min`

Supported values:

* `min` - chooses the minimum watermark reported across multiple operators

* `max` - chooses the maximum across multiple operators

Cannot be changed between query restarts from the same checkpoint location.

| spark.sql.streaming.noDataProgressEventInterval
a| [[spark.sql.streaming.noDataProgressEventInterval]] *(internal)* How long to wait between two progress events when there is no data (in millis) when `ProgressReporter` is requested to <<spark-sql-streaming-ProgressReporter.adoc#finishTrigger, finish a trigger>>

Default: `10000L`

Use <<spark-sql-streaming-SQLConf.adoc#streamingNoDataProgressEventInterval, SQLConf.streamingNoDataProgressEventInterval>> to get the current value

| spark.sql.streaming.numRecentProgressUpdates
a| [[spark.sql.streaming.numRecentProgressUpdates]] Number of link:spark-sql-streaming-ProgressReporter.adoc#updateProgress[progress updates to retain] for a streaming query

Default: `100`

| spark.sql.streaming.pollingDelay
a| [[spark.sql.streaming.pollingDelay]] *(internal)* Time delay (in ms) before `StreamExecution` link:spark-sql-streaming-MicroBatchExecution.adoc#runBatches-batchRunner-no-data[polls for new data when no data was available in a batch].

Default: `10`

| spark.sql.streaming.stateStore.maintenanceInterval
a| [[spark.sql.streaming.stateStore.maintenanceInterval]] The initial delay and how often to execute StateStore's link:spark-sql-streaming-StateStore.adoc#MaintenanceTask[maintenance task].

Default: `60s`

| spark.sql.streaming.stateStore.providerClass
a| [[spark.sql.streaming.stateStore.providerClass]] *(internal)* The fully-qualified class name of the <<spark-sql-streaming-StateStoreProvider.adoc#, StateStoreProvider>> implementation that manages state data in stateful streaming queries. This class must have a zero-arg constructor.

Default: <<spark-sql-streaming-HDFSBackedStateStoreProvider.adoc#, HDFSBackedStateStoreProvider>>

Use <<spark-sql-streaming-SQLConf.adoc#stateStoreProviderClass, SQLConf.stateStoreProviderClass>> to get the current value.

| spark.sql.streaming.unsupportedOperationCheck
a| [[spark.sql.streaming.unsupportedOperationCheck]] *(internal)* When enabled (`true`), `StreamingQueryManager` link:spark-sql-streaming-UnsupportedOperationChecker.adoc#checkForStreaming[makes sure that the logical plan of a streaming query uses supported operations only].

Default: `true`

|===
