== [[StateStore]] StateStore

`StateStore` is a <<contract, contract>> for...FIXME

[[contract]]
[source, scala]
----
package org.apache.spark.sql.execution.streaming.state

trait StateStore {
  def abort(): Unit
  def commit(): Long
  def get(key: UnsafeRow): UnsafeRow
  def getRange(start: Option[UnsafeRow], end: Option[UnsafeRow]): Iterator[UnsafeRowPair]
  def hasCommitted: Boolean
  def id: StateStoreId
  def iterator(): Iterator[UnsafeRowPair]
  def metrics: StateStoreMetrics
  def put(key: UnsafeRow, value: UnsafeRow): Unit
  def remove(key: UnsafeRow): Unit
  def version: Long
}
----

.StateStore Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[abort]] `abort`
|

| [[commit]] `commit`
|

| [[get]] `get`
|

| [[getRange]] `getRange`
|

| [[hasCommitted]] `hasCommitted`
|

| [[id]] `id`
|

| [[iterator]] `iterator`
|

| [[metrics]] `metrics`
|

| [[put]] `put`
|

| [[remove]] `remove`
|

| [[version]] `version`
|
|===

[[internal-registries]]
.StateStore's Internal Registries and Counters
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[loadedProviders]] `loadedProviders`
| Registry of link:spark-sql-streaming-StateStoreProvider.adoc[StateStoreProviders] per `StateStoreProviderId`

Used in...FIXME
|===

=== [[startMaintenanceIfNeeded]] Starting Periodic Maintenance Task (Unless Already Started) -- `startMaintenanceIfNeeded` Internal Method

CAUTION: FIXME

=== [[reportActiveStoreInstance]] Announcing New StateStoreProvider -- `reportActiveStoreInstance` Internal Method

CAUTION: FIXME

=== [[numKeys]] `numKeys` Method

CAUTION: FIXME

=== [[get]] Finding StateStore by StateStoreProviderId -- `get` Method

[source, scala]
----
get(
  storeProviderId: StateStoreProviderId,
  keySchema: StructType,
  valueSchema: StructType,
  indexOrdinal: Option[Int],
  version: Long,
  storeConf: StateStoreConf,
  hadoopConf: Configuration): StateStore
----

`get` finds `StateStore` for `StateStoreProviderId`.

Internally, `get` looks the `StateStoreProvider` (for `storeProviderId`) up in <<loadedProviders, loadedProviders>> registry. If not found, `get` link:spark-sql-streaming-StateStoreProvider.adoc#createAndInit[creates and initializes one].

`get` will also <<startMaintenanceIfNeeded, start the periodic maintenance task>> (unless already started) and <<reportActiveStoreInstance, announce the new StateStoreProvider>>.

In the end, `get` link:spark-sql-streaming-StateStoreProvider.adoc#getStore[gets] the `StateStore` (for the `version`).

NOTE: `get` is used exclusively when `StateStoreRDD` link:spark-sql-streaming-StateStoreRDD.adoc#compute[is computed].
