== [[IncrementalExecution]] IncrementalExecution -- QueryExecution for Streaming DataFrames

`IncrementalExecution` is a `QueryExecution` for streaming Datasets that allows for executing a <<logicalPlan, logical plan>> incrementally (and continuously).

[[preparations]]
`IncrementalExecution` defines <<state, state>> preparation rule to the parent ``QueryExecution``'s `preparations` that prepares streaming physical plans (using iteration-specific execution properties).

`IncrementalExecution` is <<creating-instance, created>> mostly when `StreamExecution` link:spark-sql-streaming-StreamExecution.adoc#runBatch[runs a batch] (and when `ExplainCommand` is executed).

[source, scala]
----
val q = spark.
  readStream.
  format("rate").
  load
scala> q.explain
== Physical Plan ==
StreamingRelation rate, [timestamp#639, value#640L]
----

[[internal-registries]]
.IncrementalExecution's Internal Registries and Counters (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[planner]] `planner`
a| `SparkPlanner` with extra planning strategies:

* link:spark-sql-streaming-StatefulAggregationStrategy.adoc[StatefulAggregationStrategy]
* link:spark-sql-streaming-FlatMapGroupsWithStateStrategy.adoc[FlatMapGroupsWithStateStrategy]
* `StreamingRelationStrategy`
* link:spark-sql-streaming-StreamingDeduplicationStrategy.adoc[StreamingDeduplicationStrategy]

| [[state]] `state`
| State preparation rule that transforms streaming physical plans (i.e. link:spark-sql-streaming-StateStoreSaveExec.adoc[StateStoreSaveExec], link:spark-sql-streaming-StreamingDeduplicateExec.adoc[StreamingDeduplicateExec] and link:spark-sql-streaming-FlatMapGroupsWithStateExec.adoc[FlatMapGroupsWithStateExec]) to add missing properties that are iteration-specific, i.e. the current batch.

Used when `IncrementalExecution` <<preparations, prepares a physical plan>> (i.e. `SparkPlan`) for execution.

| [[statefulOperatorId]] `statefulOperatorId`
a| Java's `AtomicInteger`

* `0` when `IncrementalExecution` is <<creating-instance, created>>

* Incremented...FIXME
|===

=== [[creating-instance]] Creating IncrementalExecution Instance

`IncrementalExecution` takes the following when created:

* [[sparkSession]] `SparkSession`
* [[logicalPlan]] Logical plan
* [[outputMode]] link:spark-sql-streaming-OutputMode.adoc[OutputMode]
* [[checkpointLocation]] Checkpoint directory
* [[runId]] Run id
* [[currentBatchId]] Current batch id
* [[offsetSeqMetadata]] `OffsetSeqMetadata`

`IncrementalExecution` initializes the <<internal-registries, internal registries and counters>>.
