== [[OffsetSeqMetadata]] OffsetSeqMetadata

`OffsetSeqMetadata` holds the metadata for the current values of the following:

* [[batchWatermarkMs]] *Event-time watermark* (in millis) that is used to bound the lateness of data that will processed

* [[batchTimestampMs]] *Batch timestamp* (in millis)

* [[conf]] *Batch configuration* with `spark.sql.shuffle.partitions` and link:spark-sql-streaming-properties.adoc#spark.sql.streaming.stateStore.providerClass[spark.sql.streaming.stateStore.providerClass] Spark properties

NOTE: `OffsetSeqMetadata` is used mainly when `IncrementalExecution` is link:spark-sql-streaming-IncrementalExecution.adoc#creating-instance[created].

[[relevantSQLConfs]]
`OffsetSeqMetadata` defines the following *relevantSQLConfs*:

* <<spark-sql-streaming-SQLConf.adoc#SHUFFLE_PARTITIONS, SHUFFLE_PARTITIONS>>
* <<spark-sql-streaming-SQLConf.adoc#STATE_STORE_PROVIDER_CLASS, STATE_STORE_PROVIDER_CLASS>>
* <<spark-sql-streaming-SQLConf.adoc#STREAMING_MULTIPLE_WATERMARK_POLICY, STREAMING_MULTIPLE_WATERMARK_POLICY>>
* <<spark-sql-streaming-SQLConf.adoc#FLATMAPGROUPSWITHSTATE_STATE_FORMAT_VERSION, FLATMAPGROUPSWITHSTATE_STATE_FORMAT_VERSION>>
* <<spark-sql-streaming-SQLConf.adoc#STREAMING_AGGREGATION_STATE_FORMAT_VERSION, STREAMING_AGGREGATION_STATE_FORMAT_VERSION>>

`relevantSQLConfs` are used when `OffsetSeqMetadata` is <<apply, created>> and is requested to <<setSessionConf, setSessionConf>>.

=== [[apply]] Creating OffsetSeqMetadata -- `apply` Factory Method

[source, scala]
----
apply(
  batchWatermarkMs: Long,
  batchTimestampMs: Long,
  sessionConf: RuntimeConfig): OffsetSeqMetadata
----

`apply`...FIXME

NOTE: `apply` is used when...FIXME

=== [[setSessionConf]] `setSessionConf` Method

[source, scala]
----
setSessionConf(metadata: OffsetSeqMetadata, sessionConf: RuntimeConfig): Unit
----

`setSessionConf`...FIXME

NOTE: `setSessionConf` is used when...FIXME
