== [[StateStoreRestoreExec]] StateStoreRestoreExec -- Unary Physical Operator for Restoring Streaming Aggregates

`StateStoreRestoreExec` is a unary physical operator (i.e. `UnaryExecNode`) that link:spark-sql-streaming-StateStoreReader.adoc[reads state from StateStore].

`StateStoreRestoreExec` is <<creating-instance, created>> mainly when `StatefulAggregationStrategy` link:spark-sql-streaming-StatefulAggregationStrategy.adoc#apply[plans a streaming aggregation].

[[output]]
The output schema of `StateStoreRestoreExec` is exactly the <<child, child>>'s output schema.

[source, scala]
----
...FIXME
----

[[outputPartitioning]]
The output partitioning of `StateStoreRestoreExec` is exactly the <<child, child>>'s output partitioning.

[source, scala]
----
...FIXME
----

=== [[doExecute]] Executing StateStoreRestoreExec -- `doExecute` Method

[source, scala]
----
doExecute(): RDD[InternalRow]
----

NOTE: `doExecute` is a part of `SparkPlan` contract to produce the result of a physical operator as an RDD of internal binary rows (i.e. `InternalRow`).

CAUTION: FIXME

=== [[creating-instance]] Creating StateStoreRestoreExec Instance

`StateStoreRestoreExec` takes the following when created:

* [[keyExpressions]] Catalyst expressions for keys
* [[stateInfo]] Optional `StatefulOperatorStateInfo`
* [[child]] Child physical plan (i.e. `SparkPlan`)
