== [[KeyToNumValuesStore]] KeyToNumValuesStore -- State Store (Handler) Of Join Keys And Counts

`KeyToNumValuesStore` is a <<spark-sql-streaming-StateStoreHandler.adoc#, StateStoreHandler>> (of <<spark-sql-streaming-StateStoreHandler.adoc#KeyToNumValuesType, KeyToNumValuesType>>) for <<spark-sql-streaming-SymmetricHashJoinStateManager.adoc#keyToNumValues, SymmetricHashJoinStateManager>> to manage a join state as <<longValueSchema, join keys and their count>>.

[[longValueSchema]]
`KeyToNumValuesStore` uses a schema with one field `value` of type `long`.

[[stateStore]]
`KeyToNumValuesStore` manages a <<spark-sql-streaming-StateStore.adoc#, StateStore>> internally.

[[logging]]
[TIP]
====
Enable `ALL` logging level for `org.apache.spark.sql.execution.streaming.state.SymmetricHashJoinStateManager$KeyToNumValuesStore` to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.sql.execution.streaming.state.SymmetricHashJoinStateManager$KeyToNumValuesStore=ALL
```

Refer to <<spark-sql-streaming-logging.adoc#, Logging>>.
====

=== [[get]] Looking Up Key Count For Given Key -- `get` Method

[source, scala]
----
get(key: UnsafeRow): Long
----

`get` requests the <<stateStore, StateStore>> for the <<spark-sql-streaming-StateStore.adoc#get, value for the given key>> and returns the long value at ``0``th position (of the row found) or `0`.

NOTE: `get` is used when `SymmetricHashJoinStateManager` is requested for the <<spark-sql-streaming-SymmetricHashJoinStateManager.adoc#get, values for a given key>> and <<spark-sql-streaming-SymmetricHashJoinStateManager.adoc#append, append a new value to a given key>>.

=== [[put]] Storing Key Count For Given Key -- `put` Method

[source, scala]
----
put(
  key: UnsafeRow,
  numValues: Long): Unit
----

`put` stores the `numValues` at the ``0``th position (of the internal unsafe row) and requests the <<stateStore, StateStore>> to <<spark-sql-streaming-StateStore.adoc#put, store it with the given key>>.

`put` requires that the `numValues` count is greater than `0` (or throws an `IllegalArgumentException`).

NOTE: `put` is used when `SymmetricHashJoinStateManager` is requested for the <<spark-sql-streaming-SymmetricHashJoinStateManager.adoc#append, append a new value to a given key>> and <<spark-sql-streaming-SymmetricHashJoinStateManager.adoc#updateNumValueForCurrentKey, updateNumValueForCurrentKey>>.
