== [[WatermarkSupport]] WatermarkSupport -- Contract for Watermark Support in Unary Physical Operators

`WatermarkSupport` is a <<contract, contract>> for unary physical operators (i.e. `UnaryExecNode`) to have support for watermark.

[NOTE]
====
*Watermark* (aka *"allowed lateness"*) allows to specify the threshold of late data, and lets the engine automatically track the current event time in the data to clean up old state accordingly.

Read the official documentation of Spark in http://spark.apache.org/docs/latest/structured-streaming-programming-guide.html#handling-late-data-and-watermarking[Handling Late Data and Watermarking].
====

[[properties]]
.WatermarkSupport's (Lazily-Initialized) Properties
[cols="1,3",options="header",width="100%"]
|===
| Property
| Description

| [[watermarkExpression]] `watermarkExpression`
a| Optional Catalyst expression that matches rows older than the watermark.

NOTE: Use `Dataset.withWatermark` operator to set the watermark. Refer to link:spark-sql-streaming-EventTimeWatermark.adoc[EventTimeWatermark Logical Operator].

---

When initialized, `watermarkExpression` finds link:spark-sql-streaming-EventTimeWatermark.adoc#watermarkDelayMs[spark.watermarkDelayMs] watermark attribute in the child output's metadata.

If found, `watermarkExpression` creates `evictionExpression` with the watermark attribute that is less than or equal <<eventTimeWatermark, eventTimeWatermark>>.

The watermark attribute may or may not be of type `StructType`. If it is, `watermarkExpression` uses the first field for comparison.

`watermarkExpression` prints out the following INFO message to the logs when link:spark-sql-streaming-EventTimeWatermark.adoc#watermarkDelayMs[spark.watermarkDelayMs] watermark attribute is found.

```
INFO FlatMapGroupsWithStateExec: Filtering state store on: [evictionExpression]
```

| [[watermarkPredicateForData]] `watermarkPredicateForData`
| Optional `Predicate` that uses <<watermarkExpression, watermarkExpression>> and the child output to match rows older than the watermark.

| [[watermarkPredicateForKeys]] `watermarkPredicateForKeys`
| Optional `Predicate` that uses <<keyExpressions, keyExpressions>> to match rows older than the watermark.
|===

=== [[contract]] WatermarkSupport Contract

[source, scala]
----
package org.apache.spark.sql.execution.streaming

trait WatermarkSupport extends UnaryExecNode {
  // only required methods that have no implementation
  def keyExpressions: Seq[Attribute]
  def eventTimeWatermark: Option[Long]
}
----

.WatermarkSupport Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[eventTimeWatermark]] `eventTimeWatermark`
| Used mainly in <<watermarkExpression, watermarkExpression>> to create a `LessThanOrEqual` Catalyst binary expression that matches rows older than the watermark.

| [[keyExpressions]] `keyExpressions`
| Used mainly in <<watermarkPredicateForKeys, watermarkPredicateForKeys>> to create a `Predicate` to match rows older than the watermark.

Used also in link:spark-sql-streaming-StateStoreSaveExec.adoc[StateStoreSaveExec] and link:spark-sql-streaming-StreamingDeduplicateExec.adoc[StreamingDeduplicateExec] physical operators.
|===

=== [[removeKeysOlderThanWatermark]] `removeKeysOlderThanWatermark` Internal Method

CAUTION: FIXME
