== [[StreamingDeduplicationStrategy]] StreamingDeduplicationStrategy Execution Planning Strategy for Deduplicate Logical Operator

`StreamingDeduplicationStrategy` is an execution planning strategy (i.e. `Strategy`) that link:spark-sql-streaming-IncrementalExecution.adoc#planner[IncrementalExecution] uses to <<apply, plan>> `Deduplicate` logical operators in streaming Datasets.

[NOTE]
====
link:spark-sql-streaming-Deduplicate.adoc[Deduplicate] logical operator is the result of link:spark-sql-streaming-Dataset-operators.adoc#dropDuplicates[dropDuplicates] operator.
====

`StreamingDeduplicationStrategy` is available using `SessionState`.

[source, scala]
----
spark.sessionState.planner.StreamingDeduplicationStrategy
----

[[apply]]
`StreamingDeduplicationStrategy` resolves streaming link:spark-sql-streaming-Deduplicate.adoc[Deduplicate] unary logical operators to link:spark-sql-streaming-StreamingDeduplicateExec.adoc[StreamingDeduplicateExec] physical operators.

[source, scala]
----
FIXME
----
