== [[KafkaSourceProvider]] KafkaSourceProvider

`KafkaSourceProvider` is a link:spark-sql-streaming-StreamSourceProvider.adoc[StreamSourceProvider] for link:spark-sql-streaming-KafkaSource.adoc[KafkaSource] (that acts as the source for *kafka* format).

`KafkaSourceProvider` is a link:spark-sql-DataSourceRegister.adoc[DataSourceRegister], too.

The short name of the data source is *kafka*.

`KafkaSourceProvider` requires the following options (that you can set using `option` method):

1. Exactly one option for `subscribe`, `subscribepattern` or `assign`
2. `kafka.bootstrap.servers` (that corresponds to `bootstrap.servers`)

NOTE: `KafkaSourceProvider` is part of <<spark-sql-kafka-0-10, `spark-sql-kafka-0-10` Library Dependency>>.

[source, scala]
----
// Run spark-shell with spark-sql-kafka-0-10_2.11 module

spark.readStream
  .format("kafka")
  .option("subscribe", "topic")
  .option("kafka.bootstrap.servers", "localhost:9092")
  .load
  .writeStream
  .format("console")
  .start
----

=== [[validateStreamOptions]] `validateStreamOptions` Internal Method

CAUTION: FIXME

=== [[createSource]] `createSource` Method

[source, scala]
----
createSource(
  sqlContext: SQLContext,
  metadataPath: String,
  schema: Option[StructType],
  providerName: String,
  parameters: Map[String, String]): Source
----

Internally, `createSource` first <<validateStreamOptions, validates stream options>>.

CAUTION: FIXME

NOTE: `createSource` is a part of link:spark-sql-streaming-StreamSourceProvider.adoc#createSource[StreamSourceProvider Contract] to create a streaming source for a format or system.

=== [[spark-sql-kafka-0-10]] spark-sql-kafka-0-10 Library Dependency

The new structured streaming API for Kafka is part of the `spark-sql-kafka-0-10` artifact. Add the following dependency to sbt project to use the streaming integration:

```
libraryDependencies += "org.apache.spark" %% "spark-sql-kafka-0-10" % "2.1.0"
```

[TIP]
====
`spark-sql-kafka-0-10` module is not included in the CLASSPATH of link:spark-shell.adoc[spark-shell] so you have to start it with link:spark-submit.adoc#packages[`--packages` command-line option].

```
./bin/spark-shell --packages org.apache.spark:spark-sql-kafka-0-10_2.11:2.1.0
```
====

NOTE: Replace `2.0.1` or `2.1.0-SNAPSHOT` with available version as found at http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spark-streaming-kafka-0-10_2.11%22[The Central Repository's search].
