== [[StreamingAggregationStateManager]] StreamingAggregationStateManager Contract -- State Managers for Streaming Aggregation

`StreamingAggregationStateManager` is the <<contract, contract>> of <<implementations, state managers>> that are used in streaming aggregations (with the <<spark-sql-streaming-StateStoreSaveExec.adoc#, StateStoreSaveExec>> and <<spark-sql-streaming-StateStoreRestoreExec.adoc#, StateStoreRestoreExec>> physical operators).

[[contract]]
.StreamingAggregationStateManager Contract
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| commit
a| [[commit]]

[source, scala]
----
commit(store: StateStore): Long
----

Commits all the updates to the <<spark-sql-streaming-StateStore.adoc#, state store>> and returns the new version

Used exclusively when <<spark-sql-streaming-StateStoreSaveExec.adoc#, StateStoreSaveExec>> physical operator is executed.

| get
a| [[get]]

[source, scala]
----
get(store: StateStore, key: UnsafeRow): UnsafeRow
----

Gets the current value of a non-``null`` key from the <<spark-sql-streaming-StateStore.adoc#, state store>>

Used exclusively when <<spark-sql-streaming-StateStoreRestoreExec.adoc#, StateStoreRestoreExec>> physical operator is executed.

| getKey
a| [[getKey]]

[source, scala]
----
getKey(row: UnsafeRow): UnsafeRow
----

Used when:

* <<spark-sql-streaming-StateStoreRestoreExec.adoc#, StateStoreRestoreExec>> physical operator is executed

* `StreamingAggregationStateManagerImplV1` legacy state manager is requested to <<spark-sql-streaming-StreamingAggregationStateManagerImplV1.adoc#put, put a row to a state store>>

| getStateValueSchema
a| [[getStateValueSchema]]

[source, scala]
----
getStateValueSchema: StructType
----

Gets the schema for the state values

Used when <<spark-sql-streaming-StateStoreRestoreExec.adoc#, StateStoreRestoreExec>> and <<spark-sql-streaming-StateStoreSaveExec.adoc#, StateStoreSaveExec>> physical operators are executed.

| iterator
a| [[iterator]]

[source, scala]
----
iterator(store: StateStore): Iterator[UnsafeRowPair]
----

Returns all the `UnsafeRow` key-value pairs in the <<spark-sql-streaming-StateStore.adoc#, state store>>

Used exclusively when <<spark-sql-streaming-StateStoreSaveExec.adoc#, StateStoreSaveExec>> physical operator is executed.

| keys
a| [[keys]]

[source, scala]
----
keys(store: StateStore): Iterator[UnsafeRow]
----

Returns all the keys in the <<spark-sql-streaming-StateStore.adoc#, state store>>

Used exclusively when physical operators with `WatermarkSupport` are requested to <<spark-sql-streaming-WatermarkSupport.adoc#removeKeysOlderThanWatermark-StreamingAggregationStateManager-store, removeKeysOlderThanWatermark>> (i.e. exclusively when <<spark-sql-streaming-StateStoreSaveExec.adoc#, StateStoreSaveExec>> physical operator is executed).

| put
a| [[put]]

[source, scala]
----
put(store: StateStore, row: UnsafeRow): Unit
----

Stores the row in the <<spark-sql-streaming-StateStore.adoc#, state store>>

Used exclusively when <<spark-sql-streaming-StateStoreSaveExec.adoc#, StateStoreSaveExec>> physical operator is executed.

| remove
a| [[remove]]

[source, scala]
----
remove(store: StateStore, key: UnsafeRow): Unit
----

Removes the key from the <<spark-sql-streaming-StateStore.adoc#, state store>>

Used exclusively when <<spark-sql-streaming-StateStoreSaveExec.adoc#, StateStoreSaveExec>> physical operator is executed (directly or indirectly as a <<spark-sql-streaming-WatermarkSupport.adoc#removeKeysOlderThanWatermark-StreamingAggregationStateManager-store, WatermarkSupport>>)

| values
a| [[values]]

[source, scala]
----
values(store: StateStore): Iterator[UnsafeRow]
----

Returns all the values in the <<spark-sql-streaming-StateStore.adoc#, state store>>

Used exclusively when <<spark-sql-streaming-StateStoreSaveExec.adoc#, StateStoreSaveExec>> physical operator is executed.

|===

[[supportedVersions]]
`StreamingAggregationStateManager` supports <<createStateManager, two versions of state managers for streaming aggregations>>:

* [[legacyVersion]] `1` (legacy)
* [[default]] `2` (default)

NOTE: The version of a state manager is controlled using <<spark-sql-streaming-properties.adoc#spark.sql.streaming.aggregation.stateFormatVersion, spark.sql.streaming.aggregation.stateFormatVersion>> internal configuration property.

[[implementations]]
NOTE: <<spark-sql-streaming-StreamingAggregationStateManagerBaseImpl.adoc#, StreamingAggregationStateManagerBaseImpl>> is the one and only known base implementation of the <<contract, StreamingAggregationStateManager Contract>> in Spark Structured Streaming.

NOTE: `StreamingAggregationStateManager` is a Scala *sealed trait* which means that all the <<implementations, implementations>> are in the same compilation unit (a single file).

=== [[createStateManager]] Creating StreamingAggregationStateManager Instance -- `createStateManager` Factory Method

[source, scala]
----
createStateManager(
  keyExpressions: Seq[Attribute],
  inputRowAttributes: Seq[Attribute],
  stateFormatVersion: Int): StreamingAggregationStateManager
----

`createStateManager` creates a new `StreamingAggregationStateManager` for a given `stateFormatVersion`:

* <<spark-sql-streaming-StreamingAggregationStateManagerImplV1.adoc#, StreamingAggregationStateManagerImplV1>> for `stateFormatVersion` being `1`

* <<spark-sql-streaming-StreamingAggregationStateManagerImplV2.adoc#, StreamingAggregationStateManagerImplV2>> for `stateFormatVersion` being `2`

`createStateManager` throws a `IllegalArgumentException` for any other `stateFormatVersion`:

```
Version [stateFormatVersion] is invalid
```

NOTE: `createStateManager` is used when <<spark-sql-streaming-StateStoreRestoreExec.adoc#stateManager, StateStoreRestoreExec>> and <<spark-sql-streaming-StateStoreSaveExec.adoc#stateManager, StateStoreSaveExec>> physical operators are created.
