== [[FlatMapGroupsWithState]] FlatMapGroupsWithState Unary Logical Operator

`FlatMapGroupsWithState` is a unary logical operator (`UnaryNode`) that is <<creating-instance, created>> to represent the following <<spark-sql-streaming-KeyValueGroupedDataset.adoc#, KeyValueGroupedDataset>> operators:

* <<spark-sql-streaming-KeyValueGroupedDataset.adoc#mapGroupsWithState, KeyValueGroupedDataset.mapGroupsWithState>>

* <<spark-sql-streaming-KeyValueGroupedDataset.adoc#flatMapGroupsWithState, KeyValueGroupedDataset.flatMapGroupsWithState>>

`FlatMapGroupsWithState` is resolved (_translated_) to:

* <<spark-sql-streaming-FlatMapGroupsWithStateExec.adoc#, FlatMapGroupsWithStateExec>> unary physical operator for streaming datasets (in <<spark-sql-streaming-FlatMapGroupsWithStateStrategy.adoc#, FlatMapGroupsWithStateStrategy>> execution planning strategy)

* `MapGroupsExec` physical operator for batch datasets (in `BasicOperators` execution planning strategy)

=== [[apply]] Creating SerializeFromObject with FlatMapGroupsWithState -- `apply` Factory Method

[source, scala]
----
apply[K: Encoder, V: Encoder, S: Encoder, U: Encoder](
  func: (Any, Iterator[Any], LogicalGroupState[Any]) => Iterator[Any],
  groupingAttributes: Seq[Attribute],
  dataAttributes: Seq[Attribute],
  outputMode: OutputMode,
  isMapGroupsWithState: Boolean,
  timeout: GroupStateTimeout,
  child: LogicalPlan): LogicalPlan
----

`apply` <<creating-instance, creates>> a `SerializeFromObject` logical operator with a `FlatMapGroupsWithState` as its child logical operator.

Internally, `apply` creates `SerializeFromObject` object consumer (aka unary logical operator) with `FlatMapGroupsWithState` logical plan.

Internally, `apply` finds `ExpressionEncoder` for the type `S` and creates a `FlatMapGroupsWithState` with `UnresolvedDeserializer` for the types `K` and `V`.

In the end, `apply` creates a `SerializeFromObject` object consumer with the `FlatMapGroupsWithState`.

NOTE: `apply` is used in <<spark-sql-streaming-KeyValueGroupedDataset.adoc#flatMapGroupsWithState, KeyValueGroupedDataset.flatMapGroupsWithState>> operator.

=== [[creating-instance]] Creating FlatMapGroupsWithState Instance

`FlatMapGroupsWithState` takes the following when created:

* [[func]] State function of type `(Any, Iterator[Any], LogicalGroupState[Any]) => Iterator[Any]`
* [[keyDeserializer]] Key deserializer Catalyst expression
* [[valueDeserializer]] Value deserializer Catalyst expression
* [[groupingAttributes]] Grouping attributes
* [[dataAttributes]] Data attributes
* [[outputObjAttr]] Output object attribute
* [[stateEncoder]] State `ExpressionEncoder`
* [[outputMode]] <<spark-sql-streaming-OutputMode.adoc#, Output mode>>
* [[isMapGroupsWithState]] `isMapGroupsWithState` flag (default: `false`)
* [[timeout]] <<spark-sql-streaming-GroupStateTimeout.adoc#, GroupStateTimeout>>
* [[child]] Child logical operator
