== Streaming Aggregation

In Spark Structured Streaming, a streaming query is an example of *streaming aggregation* when it was built with the following high-level operators:

* <<spark-sql-streaming-Dataset-operators.adoc#groupBy, Dataset.groupBy>>, `Dataset.rollup`, `Dataset.cube` (that simply create a `RelationalGroupedDataset`)

* <<spark-sql-streaming-Dataset-operators.adoc#groupByKey, Dataset.groupByKey>> (that simply creates a `KeyValueGroupedDataset`)

* SQL's `GROUP BY` clause (including `WITH CUBE` and `WITH ROLLUP`)

Under the covers, the high-level operators create a logical query plan with one or more `Aggregate` logical operators.

TIP: Read up on https://jaceklaskowski.gitbooks.io/mastering-spark-sql/spark-sql-LogicalPlan-Aggregate.html[Aggregate] logical operator in https://bit.ly/spark-sql-internals[The Internals of Spark SQL] book.

=== [[demos]] Demos

Use the following demos to learn more:

* <<spark-sql-streaming-demo-watermark-aggregation-append.adoc#, Demo: Streaming Watermark with Aggregation in Append Output Mode>>

* <<spark-sql-streaming-demo-groupBy-running-count-complete.adoc#, Demo: Streaming Query for Running Counts (Socket Source and Complete Output Mode)>>

* <<spark-sql-streaming-demo-kafka-data-source.adoc#, Demo: Streaming Aggregation with Kafka Data Source>>

* <<spark-sql-streaming-demo-groupByKey-count-Update.adoc#, Demo: groupByKey Streaming Aggregation in Update Mode>>

=== [[IncrementalExecution]] IncrementalExecution -- QueryExecution of Streaming Queries

In Spark Structured Streaming it is <<spark-sql-streaming-IncrementalExecution.adoc#, IncrementalExecution>> that plans streaming queries for execution.

While <<spark-sql-streaming-IncrementalExecution.adoc#executedPlan, planning a streaming query for execution>> (aka _query planning_), `IncrementalExecution` uses the <<spark-sql-streaming-StatefulAggregationStrategy.adoc#, StatefulAggregationStrategy>> execution planning strategy for planning streaming aggregations (`Aggregate` unary logical operators) as pairs of <<spark-sql-streaming-StateStoreRestoreExec.adoc#, StateStoreRestoreExec>> and <<spark-sql-streaming-StateStoreSaveExec.adoc#, StateStoreSaveExec>> physical operators.

[source,scala]
----
// FIXME: Demo a streaming aggregation query with logical and pjhysical plans
----
