== [[GroupState]] GroupState -- Per-Group State in Arbitrary Stateful Streaming Aggregation

`GroupState` is an <<contract, abstraction>> of <<implementations, per-group state>> (of any type `S`) for <<spark-sql-arbitrary-stateful-streaming-aggregation.adoc#, Arbitrary Stateful Streaming Aggregation>> (using <<spark-sql-streaming-KeyValueGroupedDataset.adoc#mapGroupsWithState, mapGroupsWithState>> or <<spark-sql-streaming-KeyValueGroupedDataset.adoc#flatMapGroupsWithState, flatMapGroupsWithState>> operators).

`GroupState` is created separately for every *group key* to hold a state as a *per-group state value*.

[[implementations]]
NOTE: <<spark-sql-streaming-GroupStateImpl.adoc#, GroupStateImpl>> is the default and only known implementation of the <<contract, GroupState Contract>> in Spark Structured Streaming.

[[contract]]
.GroupState Contract
[cols="30m,70",options="header",width="100%"]
|===
| Method
| Description

| exists
a| [[exists]]

[source, scala]
----
exists: Boolean
----

Checks whether the state value exists or not

If not exists, <<get, get>> throws a `NoSuchElementException`. Use <<getOption, getOption>> instead.

| get
a| [[get]]

[source, scala]
----
get: S
----

Gets the state value if it <<exists, exists>> or throws a `NoSuchElementException`

| getCurrentProcessingTimeMs
a| [[getCurrentProcessingTimeMs]]

[source, scala]
----
getCurrentProcessingTimeMs(): Long
----

Gets the current processing time (as milliseconds in epoch time)

| getCurrentWatermarkMs
a| [[getCurrentWatermarkMs]]

[source, scala]
----
getCurrentWatermarkMs(): Long
----

Gets the current event time watermark (as milliseconds in epoch time)

| getOption
a| [[getOption]]

[source, scala]
----
getOption: Option[S]
----

Gets the state value as a Scala `Option` (regardless whether it <<exists, exists>> or not)

Used when:

* `InputProcessor` is requested to `callFunctionAndUpdateState` (when the row iterator is consumed and a state value has been updated, removed or timeout changed)

* `GroupStateImpl` is requested for the <<spark-sql-streaming-GroupStateImpl.adoc#toString, textual representation>>

| hasTimedOut
a| [[hasTimedOut]]

[source, scala]
----
hasTimedOut: Boolean
----

Whether the state (for a given key) has timed out or not.

Can only be `true` when timeouts are enabled using <<setTimeoutDuration, setTimeoutDuration>>

| remove
a| [[remove]]

[source, scala]
----
remove(): Unit
----

Removes the state

| setTimeoutDuration
a| [[setTimeoutDuration]]

[source, scala]
----
setTimeoutDuration(durationMs: Long): Unit
setTimeoutDuration(duration: String): Unit
----

Specifies the *timeout duration* for the state key (in millis or as a string, e.g. "10 seconds", "1 hour") for <<spark-sql-streaming-GroupStateTimeout.adoc#ProcessingTimeTimeout, GroupStateTimeout.ProcessingTimeTimeout>>

| setTimeoutTimestamp
a| [[setTimeoutTimestamp]]

[source, scala]
----
setTimeoutTimestamp(timestamp: java.sql.Date): Unit
setTimeoutTimestamp(
  timestamp: java.sql.Date,
  additionalDuration: String): Unit
setTimeoutTimestamp(timestampMs: Long): Unit
setTimeoutTimestamp(
  timestampMs: Long,
  additionalDuration: String): Unit
----

Specifies the *timeout timestamp* for the state key for <<spark-sql-streaming-GroupStateTimeout.adoc#EventTimeTimeout, GroupStateTimeout.EventTimeTimeout>>

| update
a| [[update]]

[source, scala]
----
update(newState: S): Unit
----

Updates the state (sets the state to a new value)

|===
