== [[StreamSourceProvider]] StreamSourceProvider -- Streaming Data Source Provider

`StreamSourceProvider` is the <<contract, contract>> of <<implementations, data source providers>> that can <<createSource, create a streaming data source>> for a format (e.g. text file) or system (e.g. Apache Kafka).

[[contract]]
.StreamSourceProvider Contract
[cols="1m,3",options="header",width="100%"]
|===
| Method
| Description

| createSource
a| [[createSource]]

[source, scala]
----
createSource(
  sqlContext: SQLContext,
  metadataPath: String,
  schema: Option[StructType],
  providerName: String,
  parameters: Map[String, String]): Source
----

Creates a <<spark-sql-streaming-Source.adoc#, streaming source>> for a format or system (to continually read data)

NOTE: `metadataPath` is the value of the optional user-specified `checkpointLocation` option or resolved by link:spark-sql-streaming-StreamingQueryManager.adoc#createQuery[StreamingQueryManager].

Used exclusively when `DataSource` is requested to <<spark-sql-streaming-DataSource.adoc#createSource, create a streaming source>> (when `MicroBatchExecution` is requested to <<spark-sql-streaming-MicroBatchExecution.adoc#logicalPlan, initialize the analyzed logical plan>>)

| sourceSchema
a| [[sourceSchema]]

[source, scala]
----
sourceSchema(
  sqlContext: SQLContext,
  schema: Option[StructType],
  providerName: String,
  parameters: Map[String, String]): (String, StructType)
----

Describes a <<spark-sql-streaming-Source.adoc#, streaming source>> with a name and the schema

Used exclusively when `DataSource` is requested to <<spark-sql-streaming-DataSource.adoc#sourceSchema, describe the name and the schema of a streaming source>> (when `MicroBatchExecution` is requested to <<spark-sql-streaming-MicroBatchExecution.adoc#logicalPlan, initialize the analyzed logical plan>>)

|===

NOTE: `StreamSourceProvider` is an experimental contract.

[[implementations]]
NOTE: <<spark-sql-streaming-KafkaSourceProvider.adoc#, KafkaSourceProvider>> is the default implementation of the <<contract, StreamSourceProvider Contract>> in Spark Structured Streaming.
