== [[GroupStateImpl]] GroupStateImpl

`GroupStateImpl` is the default and only known <<spark-sql-streaming-GroupState.adoc#, GroupState>> in Spark Structured Streaming.

`GroupStateImpl` holds per-group <<optionalValue, state value>> of type `S` per group key.

`GroupStateImpl` is <<creating-instance, created>> when `GroupStateImpl` helper object is requested for the following:

* <<createForStreaming, createForStreaming>>

* <<createForBatch, createForBatch>>

=== [[creating-instance]] Creating GroupStateImpl Instance

`GroupStateImpl` takes the following to be created:

* [[optionalValue]] State value (of type `S`)
* [[batchProcessingTimeMs]] `batchProcessingTimeMs`
* [[eventTimeWatermarkMs]] `eventTimeWatermarkMs`
* [[timeoutConf]] <<spark-sql-streaming-GroupStateTimeout.adoc#, GroupStateTimeout>>
* [[hasTimedOut]] `hasTimedOut` flag
* [[watermarkPresent]] `watermarkPresent` flag

`GroupStateImpl` initializes the <<internal-properties, internal properties>>.

=== [[createForStreaming]] `createForStreaming` Factory Method

[source, scala]
----
createForStreaming[S](
  optionalValue: Option[S],
  batchProcessingTimeMs: Long,
  eventTimeWatermarkMs: Long,
  timeoutConf: GroupStateTimeout,
  hasTimedOut: Boolean,
  watermarkPresent: Boolean): GroupStateImpl[S]
----

`createForStreaming` simply creates a <<creating-instance, new GroupStateImpl>> with the given input arguments.

NOTE: `createForStreaming` is used exclusively when `InputProcessor` is requested to <<spark-sql-streaming-InputProcessor.adoc#callFunctionAndUpdateState, callFunctionAndUpdateState>> (when `InputProcessor` is requested to <<spark-sql-streaming-InputProcessor.adoc#processNewData, processNewData>> and <<spark-sql-streaming-InputProcessor.adoc#processTimedOutState, processTimedOutState>>).

=== [[createForBatch]] `createForBatch` Factory Method

[source, scala]
----
createForBatch(
  timeoutConf: GroupStateTimeout,
  watermarkPresent: Boolean): GroupStateImpl[Any]
----

`createForBatch`...FIXME

NOTE: `createForBatch` is used when...FIXME

=== [[toString]] Textual Representation -- `toString` Method

[source, scala]
----
toString: String
----

NOTE: `toString` is part of the link:++https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Object.html#toString()++[java.lang.Object] contract for the string representation of the object.

`toString`...FIXME

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| value
a| [[value]] FIXME

Used when...FIXME

| defined
a| [[defined]] FIXME

Used when...FIXME

| updated
a| [[updated]] FIXME

Default: `false`

Used when...FIXME

| removed
a| [[removed]] FIXME

Default: `false`

Used when...FIXME

| timeoutTimestamp
a| [[timeoutTimestamp]] FIXME

[[NO_TIMESTAMP]] Default: `-1`

Used when...FIXME

|===
