== [[StreamingAggregationStateManagerImplV2]] StreamingAggregationStateManagerImplV2 -- Default State Manager for Streaming Aggregations

`StreamingAggregationStateManagerImplV2` is the default <<spark-sql-streaming-StreamingAggregationStateManagerBaseImpl.adoc#, state manager for streaming aggregations>>.

NOTE: The version of a state manager is controlled using <<spark-sql-streaming-properties.adoc#spark.sql.streaming.aggregation.stateFormatVersion, spark.sql.streaming.aggregation.stateFormatVersion>> internal configuration property.

`StreamingAggregationStateManagerImplV2` is <<creating-instance, created>> exclusively when `StreamingAggregationStateManager` is requested for a <<spark-sql-streaming-StreamingAggregationStateManager.adoc#createStateManager, new StreamingAggregationStateManager>>.

=== [[put]] Storing Row in State Store -- `put` Method

[source, scala]
----
put(store: StateStore, row: UnsafeRow): Unit
----

NOTE: `put` is part of the <<spark-sql-streaming-StreamingAggregationStateManager.adoc#put, StreamingAggregationStateManager Contract>> to store a row in a state store.

`put`...FIXME

=== [[creating-instance]] Creating StreamingAggregationStateManagerImplV2 Instance

`StreamingAggregationStateManagerImplV2` takes the following when created:

* [[keyExpressions]] Attribute expressions for keys (`Seq[Attribute]`)
* [[inputRowAttributes]] Attribute expressions for input rows (`Seq[Attribute]`)
