== [[ContinuousReader]] ContinuousReader Contract -- Continuous Source in Continuous Stream Processing

`ContinuousReader` is the <<contract, extension>> of Spark SQL's `DataSourceReader` (and <<spark-sql-streaming-BaseStreamingSource.adoc#, BaseStreamingSource>>) contracts for <<implementations, data source readers>> that manage offsets in <<spark-sql-streaming-continuous-stream-processing.adoc#, Continuous Stream Processing>>.

[[contract]]
.ContinuousReader Contract
[cols="1m,3",options="header",width="100%"]
|===
| Method
| Description

| commit
a| [[commit]]

[source, java]
----
void commit(Offset end)
----

Commits the specified <<spark-sql-streaming-Offset.adoc#, offset>>

Used exclusively when `ContinuousExecution` is requested to <<spark-sql-streaming-ContinuousExecution.adoc#commit, commit an epoch>>

| deserializeOffset
a| [[deserializeOffset]]

[source, java]
----
Offset deserializeOffset(String json)
----

Deserializes an <<spark-sql-streaming-Offset.adoc#, offset>> from JSON representation

Used when `ContinuousExecution` is requested to <<spark-sql-streaming-ContinuousExecution.adoc#runContinuous, run a streaming query>> and <<spark-sql-streaming-ContinuousExecution.adoc#commit, commit an epoch>>

| getStartOffset
a| [[getStartOffset]]

[source, java]
----
Offset getStartOffset()
----

NOTE: Used exclusively in tests.

| mergeOffsets
a| [[mergeOffsets]]

[source, java]
----
Offset mergeOffsets(PartitionOffset[] offsets)
----

Used exclusively when `ContinuousExecution` is requested to <<spark-sql-streaming-ContinuousExecution.adoc#addOffset, addOffset>>

| needsReconfiguration
a| [[needsReconfiguration]]

[source, java]
----
boolean needsReconfiguration()
----

Indicates that the reader needs reconfiguration (e.g. to generate new input partitions)

Used exclusively when `ContinuousExecution` is requested to <<spark-sql-streaming-ContinuousExecution.adoc#runContinuous, run a streaming query in continuous mode>>

| setStartOffset
a| [[setStartOffset]]

[source, java]
----
void setStartOffset(Optional<Offset> start)
----

Used exclusively when `ContinuousExecution` is requested to <<spark-sql-streaming-ContinuousExecution.adoc#runContinuous, run the streaming query in continuous mode>>.

|===

[[implementations]]
.ContinuousReaders
[cols="1,2",options="header",width="100%"]
|===
| ContinuousReader
| Description

| <<spark-sql-streaming-ContinuousMemoryStream.adoc#, ContinuousMemoryStream>>
| [[ContinuousMemoryStream]]

| <<spark-sql-streaming-KafkaContinuousReader.adoc#, KafkaContinuousReader>>
| [[KafkaContinuousReader]]

| <<spark-sql-streaming-RateStreamContinuousReader.adoc#, RateStreamContinuousReader>>
| [[RateStreamContinuousReader]]

| TextSocketContinuousReader
| [[TextSocketContinuousReader]]

|===
