== Stateful Stream Processing

NOTE: Consider this page as _work in progress_ until the note disappears.

*Stateful Stream Processing* is a stream processing with some state (implicit or explicit).

In Spark Structured Streaming, a streaming query is stateful when it uses the following operators (or their SQL variants):

* <<spark-sql-streaming-Dataset-operators.adoc#groupBy, Dataset.groupBy>>
* <<spark-sql-streaming-Dataset-operators.adoc#groupByKey, Dataset.groupByKey>>
* <<spark-sql-streaming-Dataset-operators.adoc#dropDuplicates, Dataset.dropDuplicates>>
* `Dataset.join`
* ...

=== [[IncrementalExecution]] IncrementalExecution -- QueryExecution of Streaming Queries

Regardless of the query language (<<spark-sql-streaming-Dataset-operators.adoc#, Dataset API>> or SQL), any structured query (incl. streaming queries) becomes a logical query plan.

In Spark Structured Streaming it is <<spark-sql-streaming-IncrementalExecution.adoc#, IncrementalExecution>> that plans streaming queries for execution.

While <<spark-sql-streaming-IncrementalExecution.adoc#executedPlan, planning a streaming query for execution>> (aka _query planning_), `IncrementalExecution` uses the <<spark-sql-streaming-IncrementalExecution.adoc#state, state preparation rule>>. The rule fills out the following physical operators with the execution-specific configuration (with <<spark-sql-streaming-IncrementalExecution.adoc#nextStatefulOperationStateInfo, StatefulOperatorStateInfo>> being the most important for stateful stream processing):

* <<spark-sql-streaming-StateStoreSaveExec.adoc#, StateStoreSaveExec>> (used for <<spark-sql-streaming-aggregation.adoc#, streaming aggregation>>)
* <<spark-sql-streaming-StateStoreRestoreExec.adoc#, StateStoreRestoreExec>>
* <<spark-sql-streaming-StreamingDeduplicateExec.adoc#, StreamingDeduplicateExec>>
* <<spark-sql-streaming-FlatMapGroupsWithStateExec.adoc#, FlatMapGroupsWithStateExec>>
* <<spark-sql-streaming-StreamingSymmetricHashJoinExec.adoc#, StreamingSymmetricHashJoinExec>>
* <<spark-sql-streaming-StreamingGlobalLimitExec.adoc#, StreamingGlobalLimitExec>>

=== State Management

The state in a stateful streaming query can be implicit or explicit.
