== [[HDFSBackedStateStoreProvider]] HDFSBackedStateStoreProvider

`HDFSBackedStateStoreProvider` is the one and only known <<spark-sql-streaming-StateStoreProvider.adoc#, StateStoreProvider>>.

[[baseDir]]
`HDFSBackedStateStoreProvider` uses the *state checkpoint base directory* (that is the <<spark-sql-streaming-StateStoreId.adoc#storeCheckpointLocation, storeCheckpointLocation>> of the <<stateStoreId, StateStoreId>>) for <<deltaFile, delta>> and <<snapshotFile, snapshot>> state files. The checkpoint directory is created when `HDFSBackedStateStoreProvider` is requested to <<init, initialize>>.

[[stateStoreId]]
`HDFSBackedStateStoreProvider` uses `stateStoreId` that...FIXME

[[toString]]
When requested for the textual representation, `HDFSBackedStateStoreProvider`...FIXME

[[internal-registries]]
.HDFSBackedStateStoreProvider's Internal Properties
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| loadedMaps
a| [[loadedMaps]]

[source, scala]
----
loadedMaps: TreeMap[Long, ConcurrentHashMap[UnsafeRow, UnsafeRow]]
----

Java's https://docs.oracle.com/javase/8/docs/api/java/util/TreeMap.html[TreeMap] of FIXME sorted according to the reversed natural ordering of the keys

A new entry (a version and the associated map) is added when `HDFSBackedStateStoreProvider` is requested to <<putStateIntoStateCacheMap, putStateIntoStateCacheMap>>

Used when...FIXME
|===

[[logging]]
[TIP]
====
Enable `DEBUG`, `INFO` or `WARN` logging level for `org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider=DEBUG
```

Refer to link:spark-sql-streaming-logging.adoc[Logging].
====

=== [[getStore]] Retrieving State Store for Version -- `getStore` Method

[source, scala]
----
getStore(version: Long): StateStore
----

NOTE: `getStore` is part of the <<spark-sql-streaming-StateStoreProvider.adoc#getStore, StateStoreProvider Contract>> to get the <<spark-sql-streaming-StateStore.adoc#, StateStore>> for a given version.

`getStore`...FIXME

=== [[deltaFile]] `deltaFile` Internal Method

[source, scala]
----
deltaFile(version: Long): Path
----

`deltaFile` creates a Hadoop https://hadoop.apache.org/docs/r2.7.3/api/org/apache/hadoop/fs/Path.html[Path] of the `[version].delta` file in the <<baseDir, baseDir>>.

NOTE: `deltaFile` is used when...FIXME

=== [[fetchFiles]] `fetchFiles` Internal Method

[source, scala]
----
fetchFiles(): Seq[StoreFile]
----

`fetchFiles`...FIXME

NOTE: `fetchFiles` is used when `HDFSBackedStateStoreProvider` is requested to <<latestIterator, latestIterator>>, <<doSnapshot, doSnapshot>> and <<cleanup, cleanup>>.

=== [[init]] Initializing StateStoreProvider -- `init` Method

[source, scala]
----
init(
  stateStoreId: StateStoreId,
  keySchema: StructType,
  valueSchema: StructType,
  indexOrdinal: Option[Int],
  storeConf: StateStoreConf,
  hadoopConf: Configuration): Unit
----

NOTE: `init` is part of the <<spark-sql-streaming-StateStoreProvider.adoc#init, StateStoreProvider Contract>> to initialize itself.

`init`...FIXME

=== [[latestIterator]] `latestIterator` Internal Method

[source, scala]
----
latestIterator(): Iterator[UnsafeRowPair]
----

`latestIterator`...FIXME

NOTE: `latestIterator` seems to be used exclusively in tests.

=== [[doSnapshot]] `doSnapshot` Internal Method

[source, scala]
----
doSnapshot(): Unit
----

`doSnapshot`...FIXME

NOTE: `doSnapshot` is used when...FIXME

=== [[cleanup]] `cleanup` Internal Method

[source, scala]
----
cleanup(): Unit
----

`cleanup`...FIXME

NOTE: `cleanup` is used when...FIXME

=== [[close]] Closing State Store Provider -- `close` Method

[source, scala]
----
close(): Unit
----

NOTE: `close` is part of the <<spark-sql-streaming-StateStoreProvider.adoc#close, StateStoreProvider Contract>> to close the state store provider.

`close`...FIXME

=== [[putStateIntoStateCacheMap]] `putStateIntoStateCacheMap` Internal Method

[source, scala]
----
putStateIntoStateCacheMap(
  newVersion: Long,
  map: ConcurrentHashMap[UnsafeRow, UnsafeRow]): Unit
----

`putStateIntoStateCacheMap`...FIXME

NOTE: `putStateIntoStateCacheMap` is used when `HDFSBackedStateStoreProvider` is requested to <<commitUpdates, commitUpdates>> and <<loadMap, loadMap>>.

=== [[commitUpdates]] `commitUpdates` Internal Method

[source, scala]
----
commitUpdates(
  newVersion: Long,
  map: ConcurrentHashMap[UnsafeRow, UnsafeRow],
  output: DataOutputStream): Unit
----

`commitUpdates`...FIXME

NOTE: `commitUpdates` is used exclusively when `HDFSBackedStateStore` is requested to <<spark-sql-streaming-HDFSBackedStateStore.adoc#commit, commit state changes>>.

=== [[loadMap]] `loadMap` Internal Method

[source, scala]
----
loadMap(version: Long): ConcurrentHashMap[UnsafeRow, UnsafeRow]
----

`loadMap`...FIXME

NOTE: `loadMap` is used when `HDFSBackedStateStoreProvider` is requested to <<getStore, getStore>> and <<latestIterator, latestIterator>>.
