== [[StreamingExecutionRelation]] StreamingExecutionRelation Leaf Logical Operator to Represent Source At Execution

`StreamingExecutionRelation` is a leaf logical plan (i.e. `LogicalPlan`) that is <<creating-instance, created>> to represent a link:spark-sql-streaming-Source.adoc[source] when...FIXME

NOTE: `StreamingExecutionRelation` is resolved (aka _planned_) to link:link:spark-sql-streaming-StreamingRelationExec.adoc[StreamingRelationExec] physical operator in link:spark-sql-streaming-StreamingRelationStrategy.adoc[StreamingRelationStrategy] execution planning strategy.

=== [[creating-instance]] Creating StreamingExecutionRelation Instance

`StreamingExecutionRelation` takes the following when created:

* [[source]] link:spark-sql-streaming-Source.adoc[Streaming source]
* [[output]] Output attributes

=== [[apply]] Creating StreamingExecutionRelation (for MemoryStream Source) -- `apply` Factory Method

[source, scala]
----
apply(source: Source): StreamingExecutionRelation
----

`apply` creates a `StreamingExecutionRelation` for the input `source` and with the attributes of the link:spark-sql-streaming-Source.adoc#schema[schema] of the `source`.

NOTE: `apply` is used exclusively when `MemoryStream` link:spark-sql-streaming-MemoryStream.adoc#creating-instance[is created] (and the link:spark-sql-streaming-MemoryStream.adoc#logicalPlan[logical plan initialized]).
