== Streaming Join

[[operators]]
In Spark Structured Streaming, a *streaming join* is a streaming query that was described (_build_) using the <<spark-sql-streaming-Dataset-operators.adoc#, high-level streaming operators>>:

* <<spark-sql-streaming-Dataset-operators.adoc#crossJoin, Dataset.crossJoin>>

* <<spark-sql-streaming-Dataset-operators.adoc#join, Dataset.join>>

* <<spark-sql-streaming-Dataset-operators.adoc#joinWith, Dataset.joinWith>>

* SQL's `JOIN` clause

Streaming joins can be *stateless* or <<spark-sql-streaming-stateful-stream-processing.adoc#, stateful>>:

* Joins of a streaming query and a batch query (_stream-static joins_) are stateless and no state management is required

* Joins of two streaming queries (<<stream-stream-joins, stream-stream joins>>) are stateful and require streaming state (with an optional <<join-state-watermark, join state watermark for state removal>>).

=== [[stream-stream-joins]] Stream-Stream Joins

Spark Structured Streaming supports stream-stream joins with the following:

* <<spark-sql-streaming-StreamingJoinStrategy.adoc#, Equality predicate>> (https://en.wikipedia.org/wiki/Join_(SQL)#Equi-join[equi-joins] that use only equality comparisons in the join-predicate)

* `Inner`, `LeftOuter`, and `RightOuter` <<spark-sql-streaming-StreamingSymmetricHashJoinExec.adoc#supported-join-types, join types only>>

A stream-stream equi-join is planned as <<spark-sql-streaming-StreamingSymmetricHashJoinExec.adoc#, StreamingSymmetricHashJoinExec>> physical operator of two `ShuffleExchangeExec` physical operators (per <<spark-sql-streaming-StreamingSymmetricHashJoinExec.adoc#requiredChildDistribution, Required Partition Requirements>>).

=== [[join-state-watermark]] Join State Watermark for State Removal

Stream-stream joins may optionally define *Join State Watermark* for state removal.

* <<spark-sql-streaming-StreamingSymmetricHashJoinExec.adoc#stateWatermarkPredicates, StreamingSymmetricHashJoinExec>>

A join state watermark can be specified on the following:

. Join keys (_key state_)

. Columns of the left and right sides (_value state_)

A join state watermark can be specified on key state, value state or both.

=== [[IncrementalExecution]] IncrementalExecution -- QueryExecution of Streaming Queries

Under the covers, the <<operators, high-level operators>> create a logical query plan with one or more `Join` logical operators.

TIP: Read up on https://jaceklaskowski.gitbooks.io/mastering-spark-sql/spark-sql-LogicalPlan-Join.html[Join Logical Operator] in https://bit.ly/spark-sql-internals[The Internals of Spark SQL] online book.

In Spark Structured Streaming <<spark-sql-streaming-IncrementalExecution.adoc#, IncrementalExecution>> is responsible for planning streaming queries for execution.

At <<spark-sql-streaming-IncrementalExecution.adoc#executedPlan, query planning>>, `IncrementalExecution` uses the <<spark-sql-streaming-StreamingJoinStrategy.adoc#, StreamingJoinStrategy>> execution planning strategy for planning <<stream-stream-joins, stream-stream joins>> as <<spark-sql-streaming-StreamingSymmetricHashJoinExec.adoc#, StreamingSymmetricHashJoinExec>> physical operators.

=== [[demos]] Demos

Use the following demos to learn more:

* <<spark-sql-streaming-demo-join-stream-stream-StreamingSymmetricHashJoinExec.adoc#, Demo: Streaming Join of Streaming Queries and StreamingSymmetricHashJoinExec Physical Operator>>

=== [[i-want-more]] Further Reading Or Watching

* https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html#stream-stream-joins[Stream-stream Joins] in the official documentation of Apache Spark for Structured Streaming

* https://databricks.com/blog/2018/03/13/introducing-stream-stream-joins-in-apache-spark-2-3.html[Introducing Stream-Stream Joins in Apache Spark 2.3] by Databricks

* (video) https://databricks.com/session/deep-dive-into-stateful-stream-processing-in-structured-streaming[Deep Dive into Stateful Stream Processing in Structured Streaming] by Tathagata Das
